const EXTM3U = '#EXTM3U';
const EXT_X_VERSION = '#EXT-X-VERSION';
const EXT_X_TARGETDURATION = '#EXT-X-TARGETDURATION';
const EXT_X_MEDIA_SEQUENCE = '#EXT-X-MEDIA-SEQUENCE';
const EXT_X_KEY = '#EXT-X-KEY';
const EXTINF = '#EXTINF';
const EXT_X_ENDLIST = '#EXT-X-ENDLIST';
